source:
  - name: openwrt
    url: https://github.com/openwrt/openwrt.git
    branch: 
    revision: bedcaabe6d0586fabab72aa1fc6c06b8f83b6dfa0c
  - name: gl_sdk
    url: 
    branch: 
    revision: 

patch_folders:
  - patches
