source:
  - name: openwrt
    url: https://github.com/openwrt/openwrt.git
    revision: bcaabe6d0586fabab72aa1fc6c06b8f83b6dfa0c
  - name: gl_sdk
    url: https://github.com/gl-inet/glinet4.x.git
  - name: feeds
    url: https://github.com/njitwb/feeds

patch_folders:
  - devices/mt2500/patches

files_folders:
  - devices/mt2500/files
